# Generated by Django 3.1.8 on 2021-12-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_p_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='public_review',
        ),
    ]
