# Generated by Django 3.1.8 on 2021-12-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211207_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='public_review',
            name='rate',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
