# Generated by Django 3.1.8 on 2021-12-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_all_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_cart',
            name='photo',
        ),
    ]
