# Generated by Django 3.1.8 on 2021-12-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_all_cart_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='garder_collection',
            new_name='garden_collection',
        ),
    ]
