# Generated by Django 3.1.8 on 2021-12-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_public_contact_public_review_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_contact',
            name='public_review_unique',
            field=models.IntegerField(null=True),
        ),
    ]
