# Generated by Django 3.1.8 on 2021-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211207_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public_contact',
            name='public_review_unique',
        ),
        migrations.AddField(
            model_name='public_review',
            name='public_review_unique',
            field=models.IntegerField(null=True),
        ),
    ]
