# Generated by Django 3.1.8 on 2021-12-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_garden_collection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('title', models.CharField(max_length=99)),
                ('blog', models.TextField()),
            ],
        ),
    ]
