# Generated by Django 3.1.8 on 2021-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_all_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_blog',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
