# Generated by Django 3.1.8 on 2021-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_all_blog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('project_details', models.CharField(max_length=99)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
