# Generated by Django 3.1.8 on 2021-12-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_roof_top_garden'),
    ]

    operations = [
        migrations.CreateModel(
            name='your_garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('category', models.CharField(max_length=99, null=True)),
                ('price', models.CharField(max_length=99)),
                ('serial', models.CharField(max_length=99)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.DeleteModel(
            name='roof_top_garden',
        ),
    ]
