# Generated by Django 3.1.8 on 2021-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211210_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_cart',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
