# Generated by Django 3.1.8 on 2021-12-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211211_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_collection',
            name='category',
            field=models.CharField(choices=[('garden', 'garden'), ('tree', 'tree'), ('vegetable', 'vegetable'), ('flower', 'flower'), ('fruit', 'fruit')], default='green', max_length=99),
        ),
        migrations.AlterField(
            model_name='garden_collection',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
