# Generated by Django 3.1.8 on 2021-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211211_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
