# Generated by Django 3.1.8 on 2021-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211212_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_your_garden_yourself',
            name='price',
            field=models.IntegerField(),
        ),
    ]
