# Generated by Django 3.1.8 on 2021-12-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20211212_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('education', models.CharField(max_length=99)),
                ('university', models.CharField(max_length=99)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
