# Generated by Django 3.1.8 on 2021-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_your_garden_yourself',
            name='category',
            field=models.CharField(choices=[('balcony', 'balcony'), ('rooftop', 'rooftop'), ('corporate', 'corporate')], default='corporate', max_length=99, null=True),
        ),
    ]
